version: '0.0.1'
services:
  db: 
    image: postgres:15.0-alpine
    container_name: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=docker_test
      - PGDATA=/var/lib/postgresql/data/
    restart: always
  app:
    image: drucoder/web-server
    container_name: app
    ports:
      - 80:3000
    environment:
      - POSTGRES_HOST=db
    restart: always
    links:
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8989:8989